language: node_js
node_js: 
  - stable  

sudo: false
cache:
  directories:
    node_modules

install:
  - npm install -g cross-env
  - npm install -g codecov
  - npm install -g mocha

after_script:
  - npm run cov
  - codecov

script:
  - npm run test